catalog: shm
schema: petrinex
api_url: "https://www.petrinex.gov.ab.ca/publicdata/API/Files/AB/"
download_dir: "/Volumes/shm/petrinex/bronze"
start_month_yyyy_mm: "2015-01"
end_month_yyyy_mm: "2026-01"
timeout_seconds: 30
conventional:
  download: true
  code: "Vol"
  name: "Conventional Volumetric"
  table_name: "conv_bronze"
ngl:
  download: true
  code: "NGL"
  name: "NGL & Marketable Gas Volumes"
  table_name: "ngl_bronze"
  production_columns:
    - "OilProduction"
    - "GasProduction"
    - "CondensateProduction"
forecast:
  horizon_months: 30
  min_months: 6
  batch_size: 500
