catalog: shm
schema: petrinex
ingest:
  download_dir: "./petrinex_downloads"
  start_month_yyyy_mm: "2020-01"
  end_month_yyyy_mm: "2020-04"
  timeout_seconds: 30
  conventional:
    download: true
    code: "Vol"
    name: "Conventional Volumetric"
    table_name: "ConventionalVolumetric"
  ngl:
    download: true
    code: "NGL"
    name: "NGL & Marketable Gas Volumes"
    table_name: "NGLVolumetric"
process:
  conventional_table_name: ConventionalVolumetric
  ngl_table_name: NGLVolumetric
  wells_table_name: Well
forecast:
  model:
    name: petrinex
    version: 1.0.0
    type: petrinex
    parameters:
      - name: forecast_horizon
        value: 12
