catalog: shm
schema: petrinex
ingest:
  download_dir: "./petrinex_downloads" # Local directory (will be gitignored)
  start_month_yyyy_mm: "2024-01"
  end_month_yyyy_mm: "2024-02" # Just a couple months for local testing
  timeout_seconds: 30
  conventional:
    download: true
    code: "Vol"
    name: "Conventional Volumetric"
    table_name: "ConventionalVolumetric"
  ngl:
    download: false # Disable to speed up local testing
    code: "NGL"
    name: "NGL & Marketable Gas Volumes"
    table_name: "NGLVolumetric"
process:
  conventional_table_name: ConventionalVolumetric
  ngl_table_name: NGLVolumetric
  wells_table_name: Well
forecast:
  model:
    name: petrinex
    version: 1.0.0
    type: petrinex
    parameters:
      - name: forecast_horizon
        value: 12
